#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "gcp_prod"
perennials = ["gcp_uat", "gcp_release"] #test "gcp_test_2 later"

[create]
# Comment out as we want feature branches over perennials for now
# new-branch-type = 'perennial'
