#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "gcp_prod"
perennial = ["gcp_uat"]

[create]
new-branch-type = 'feature'
